### ISSUE TITLE
NoClassDefFoundError: com/sun/security/auth/module/UnixSystem on Linux

### ISSUE THREAD

**Issue by amir1376** [vinceglb/FileKit#107]
Hi there first of all thanks for your great work. 

When I want to open Directory Picker I get this error

**Affected platform**: `Ubuntu 24.04.1 LTS`

Here is the stack trace.
```
java.lang.NoClassDefFoundError: com/sun/security/auth/module/UnixSystem
    at org.freedesktop.dbus.connections.SASL.getUserId(SASL.java:758)
    at org.freedesktop.dbus.connections.SASL.auth(SASL.java:460)
    at org.freedesktop.dbus.connections.transports.AbstractTransport.authenticate(AbstractTransport.java:254)
    at org.freedesktop.dbus.connections.transports.AbstractTransport.internalConnect(AbstractTransport.java:230)
    at org.freedesktop.dbus.connections.transports.AbstractTransport.connect(AbstractTransport.java:177)
    at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:226)
    at org.freedesktop.dbus.connections.base.AbstractConnectionBase.<init>(AbstractConnectionBase.java:118)
    at org.freedesktop.dbus.connections.base.ConnectionMethodInvocation.<init>(ConnectionMethodInvocation.java:35)
    at org.freedesktop.dbus.connections.base.DBusBoundPropertyHandler.<init>(DBusBoundPropertyHandler.java:46)
    at org.freedesktop.dbus.connections.base.ConnectionMessageHandler.<init>(ConnectionMessageHandler.java:34)
    at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:40)
    at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:73)
    at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.build(DBusConnectionBuilder.java:176)
    at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal.isAvailable(XdgFilePickerPortal.kt:32)
    at io.github.vinceglb.filekit.core.platform.linux.LinuxFilePicker.xdgFilePickerPortalAvailable_delegate$lambda$0(LinuxFilePicker.kt:22)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.github.vinceglb.filekit.core.platform.linux.LinuxFilePicker.getXdgFilePickerPortalAvailable(LinuxFilePicker.kt:22)
    at io.github.vinceglb.filekit.core.platform.linux.LinuxFilePicker.pickDirectory(LinuxFilePicker.kt:53)
    at io.github.vinceglb.filekit.core.FileKit$pickDirectory$2.invokeSuspend(FileKit.jvm.kt:50)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Caused by: java.lang.ClassNotFoundException: com.sun.security.auth.module.UnixSystem
    ... 27 more
```
I only see this problem in linux. ( it works nice in Windows! )

If you want to reproduce that error.
1. Clone my repository and checkout `v1.0.9` ( I'm using this library since `v1.0.9` )
```
https://github.com/amir1376/ab-download-manager
```
2. I am using [JBR 17](https://github.com/JetBrains/JetBrainsRuntime/releases) as `project JDK`.
3. Run the app
```bash
./gradlew desktop:app:runReleaseDistributable
```
4. Open a `Directory Picker` ( for example go to `Setting > Download Engine > Default Download Folder` ) 
5. The app will show that error!

Let me know if I can help. thanks again.

**Comment by HansHolz09** [comment]
I had exactly the same problem, try this: https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials%2FNative_distributions_and_local_execution%2FREADME.md#configuring-included-jdk-modules

**Comment by Snd-R** [comment]
You just need `jdk.security.auth` module
It's possible to just add this module for linux distribution
```
compose.desktop {
    application {
        nativeDistributions {
            linux {
                modules("jdk.security.auth")
            }
        }
    }
}
```

Should probably add it somewhere in readme

**Comment by amir1376** [comment]
Thank you guys.

adding `jdk.security.auth` module fixes the problem so I close this as completed!

**Comment by vinceglb** [comment]
Thanks guys for your help! I'm going to add this to the readme
