### ISSUE TITLE
 java.net.URISyntaxException: Illegal character in path

### ISSUE THREAD

**Issue by dikhawk** [vinceglb/FileKit#129]
Hi, I updated the library **io.github.vinceglb:filekit-core** from **_0.6.2_** to **_0.8.2_**, and after the update, I have a problem with the file name, but before the update, it worked fine. When I select a file named **_Ubuntu [24.04].torrent_**, an exception is thrown:

### Exception in thread "DBus-Signal-Receiver-1" java.net.URISyntaxException: Illegal character in path at index 96: file:///home/dik/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9%20%D1%81%D1%82%D0%BE%D0%BB/Ubuntu%20[24.04].torrent
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal$ResponseHandler.handle(XdgFilePickerPortal.kt:180)
	at org.freedesktop.dbus.connections.base.ConnectionMessageHandler.lambda$handleMessage$1(ConnectionMessageHandler.java:107)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

If I change the file name to _**Ubuntu 24.04.torrent**_, everything works fine.
I suppose the problem is with these characters: '**_[]_**'.

**_Platform: Java Desktop, Linux Manjaro_**

**Comment by vinceglb** [comment]
Hi @dikhawk! Thanks for creating this issue. I'll take a look!

**Comment by vinceglb** [comment]
I'm going to push a fix soon 👌

**Comment by vinceglb** [comment]
Does version 0.8.5 fix the problem?

**Comment by dikhawk** [comment]
No.
### Exception in thread "DefaultDispatcher-worker-9" java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.io.File.<init>(Unknown Source)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal.pickFiles(XdgFilePickerPortal.kt:116)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal.access$pickFiles(XdgFilePickerPortal.kt:29)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal$pickFiles$2.invokeSuspend(XdgFilePickerPortal.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4fafad55, Dispatchers.Default]

**Comment by vinceglb** [comment]
@dikhawk Can you try version 0.8.7 please?

**Comment by dikhawk** [comment]
Now it's fine. Thank you.
