### ISSUE TITLE
ClassCastException on desktop when canceling pick dialog

### ISSUE THREAD

**Issue by zacharee** [vinceglb/FileKit#89]
When closing the file picker dialog and canceling it by pressing escape, the following Exception gets thrown and the result is never returned to the caller.

```
Exception in thread "DBus-Signal-Receiver-1" java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.freedesktop.dbus.DBusMap (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.freedesktop.dbus.DBusMap is in unnamed module of loader 'app')
        at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal$ResponseHandler.handle(XdgFilePickerPortal.kt:177)
        at org.freedesktop.dbus.connections.base.ConnectionMessageHandler.lambda$handleMessage$1(ConnectionMessageHandler.java:107)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by zacharee** [comment]
Actually it looks like this happens on any result from the XDG picker.

**Comment by vinceglb** [comment]
Thanks for reporting this bug! And thanks again for your PR! I'm going to push a new release with all your fixes.
